### ISSUE TITLE
Better site for next year

### ISSUE THREAD

**Issue by 1995parham** [AUT-ICPC/webApp#2]
I think it's a good idea to correct some issues for next year:

1. we need a simple script for creating the admin account in MongoDB for easier setup.
2. adds export to Microsoft Excel button

**Comment by kimiarm** [comment]
what is your exact idea for #1 ?

can you send me your script for send group emails  ?

**Comment by 1995parham** [comment]
All scripts for import/export related things is [here](https://github.com/AUT-ICPC/imex). for 1 I think first of all @anewage must tell us how we can create the admin user and then we can create python script for that.

**Comment by 1995parham** [comment]
@kimiarm Thanks for adding support of tsv.
